# Generated by Django 2.2.5 on 2019-09-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemirestapp', '0002_university'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='university',
            table='University',
        ),
    ]
