# Generated by Django 2.2.5 on 2019-09-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemirestapp', '0003_auto_20190910_2337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='songs',
            table='songs',
        ),
        migrations.AlterModelTable(
            name='university',
            table='university',
        ),
    ]
