# Generated by Django 2.2.5 on 2019-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemirestapp', '0004_auto_20190910_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetypeid', models.CharField(max_length=50)),
                ('casetypename', models.CharField(max_length=50)),
                ('createddatetime', models.DateTimeField(max_length=50)),
            ],
            options={
                'verbose_name': 'CaseType',
                'verbose_name_plural': 'CaseTypes',
                'db_table': 'CaseType',
            },
        ),
        migrations.CreateModel(
            name='CaseTypeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetypedetailid', models.CharField(max_length=50)),
                ('casetypedetailname', models.CharField(max_length=50)),
                ('displaymsg', models.CharField(max_length=250)),
                ('displaysubmsg', models.CharField(max_length=250)),
                ('filepath', models.CharField(max_length=250)),
                ('isplaying', models.BooleanField(max_length=4)),
                ('createddatetime', models.DateTimeField(max_length=50)),
            ],
            options={
                'verbose_name': 'CaseTypeDetail',
                'verbose_name_plural': 'CaseTypeDetails',
                'db_table': 'CaseTypeDetail',
            },
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
