# Generated by Django 2.2.5 on 2019-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemirestapp', '0006_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetypedetail',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casetypedetail',
            name='filepath',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
